version: '3.8'

services:
    postgres:
      image: postgres:latest
      container_name: the-rougue-dev-db
      environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: always

volumes:
  postgres_data: