spring:
  application:
    name: the-rougue-dev-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

the-rougue-dev:
  security:
    secret: ${SECRET}
    cookie-secure: false